export const COUNTRIES = [
    { value: 'AR', label: '🇦🇷 Argentina', flag: '🇦🇷' },
    { value: 'BO', label: '🇧🇴 Bolivia', flag: '🇧🇴' },
    { value: 'BR', label: '🇧🇷 Brazil', flag: '🇧🇷' },
    { value: 'CA', label: '🇨🇦 Canada', flag: '🇨🇦' },
    { value: 'CL', label: '🇨🇱 Chile', flag: '🇨🇱' },
    { value: 'CO', label: '🇨🇴 Colombia', flag: '🇨🇴' },
    { value: 'CR', label: '🇨🇷 Costa Rica', flag: '🇨🇷' },
    { value: 'CU', label: '🇨🇺 Cuba', flag: '🇨🇺' },
    { value: 'DO', label: '🇩🇴 Dominican Republic', flag: '🇩🇴' },
    { value: 'EC', label: '🇪🇨 Ecuador', flag: '🇪🇨' },
    { value: 'SV', label: '🇸🇻 El Salvador', flag: '🇸🇻' },
    { value: 'ES', label: '🇪🇸 Spain', flag: '🇪🇸' },
    { value: 'GT', label: '🇬🇹 Guatemala', flag: '🇬🇹' },
    { value: 'HT', label: '🇭🇹 Haiti', flag: '🇭🇹' },
    { value: 'HN', label: '🇭🇳 Honduras', flag: '🇭🇳' },
    { value: 'JM', label: '🇯🇲 Jamaica', flag: '🇯🇲' },
    { value: 'MX', label: '🇲🇽 Mexico', flag: '🇲🇽' },
    { value: 'NI', label: '🇳🇮 Nicaragua', flag: '🇳🇮' },
    { value: 'PA', label: '🇵🇦 Panama', flag: '🇵🇦' },
    { value: 'PY', label: '🇵🇾 Paraguay', flag: '🇵🇾' },
    { value: 'PE', label: '🇵🇪 Peru', flag: '🇵🇪' },
    { value: 'PR', label: '🇵🇷 Puerto Rico', flag: '🇵🇷' },
    { value: 'UY', label: '🇺🇾 Uruguay', flag: '🇺🇾' },
    { value: 'US', label: '🇺🇸 United States', flag: '🇺🇸' },
    { value: 'VE', label: '🇻🇪 Venezuela', flag: '🇻🇪' },
    { value: 'AT', label: '🇦🇹 Austria', flag: '🇦🇹' },
    { value: 'AU', label: '🇦🇺 Australia', flag: '🇦🇺' },
    { value: 'BE', label: '🇧🇪 Belgium', flag: '🇧🇪' },
    { value: 'BG', label: '🇧🇬 Bulgaria', flag: '🇧🇬' },
    { value: 'BY', label: '🇧🇾 Belarus', flag: '🇧🇾' },
    { value: 'CN', label: '🇨🇳 China', flag: '🇨🇳' },
    { value: 'DE', label: '🇩🇪 Germany', flag: '🇩🇪' },
    { value: 'DK', label: '🇩🇰 Denmark', flag: '🇩🇰' },
    { value: 'EE', label: '🇪🇪 Estonia', flag: '🇪🇪' },
    { value: 'FI', label: '🇫🇮 Finland', flag: '🇫🇮' },
    { value: 'FR', label: '🇫🇷 France', flag: '🇫🇷' },
    { value: 'GB', label: '🇬🇧 United Kingdom', flag: '🇬🇧' },
    { value: 'GR', label: '🇬🇷 Greece', flag: '🇬🇷' },
    { value: 'HR', label: '🇭🇷 Croatia', flag: '🇭🇷' },
    { value: 'HU', label: '🇭🇺 Hungary', flag: '🇭🇺' },
    { value: 'ID', label: '🇮🇩 Indonesia', flag: '🇮🇩' },
    { value: 'IE', label: '🇮🇪 Ireland', flag: '🇮🇪' },
    { value: 'IN', label: '🇮🇳 India', flag: '🇮🇳' },
    { value: 'IQ', label: '🇮🇶 Iraq', flag: '🇮🇶' },
    { value: 'IS', label: '🇮🇸 Iceland', flag: '🇮🇸' },
    { value: 'IT', label: '🇮🇹 Italy', flag: '🇮🇹' },
    { value: 'JP', label: '🇯🇵 Japan', flag: '🇯🇵' },
    { value: 'KE', label: '🇰🇪 Kenya', flag: '🇰🇪' },
    { value: 'KR', label: '🇰🇷 South Korea', flag: '🇰🇷' },
    { value: 'KW', label: '🇰🇼 Kuwait', flag: '🇰🇼' },
    { value: 'KZ', label: '🇰🇿 Kazakhstan', flag: '🇰🇿' },
    { value: 'LB', label: '🇱🇧 Lebanon', flag: '🇱🇧' },
    { value: 'LK', label: '🇱🇰 Sri Lanka', flag: '🇱🇰' },
    { value: 'LT', label: '🇱🇹 Lithuania', flag: '🇱🇹' },
    { value: 'LU', label: '🇱🇺 Luxembourg', flag: '🇱🇺' },
    { value: 'LV', label: '🇱🇻 Latvia', flag: '🇱🇻' },
    { value: 'LY', label: '🇱🇾 Libya', flag: '🇱🇾' },
    { value: 'MA', label: '🇲🇦 Morocco', flag: '🇲🇦' },
    { value: 'MD', label: '🇲🇩 Moldova', flag: '🇲🇩' },
    { value: 'ME', label: '🇲🇪 Montenegro', flag: '🇲🇪' },
    { value: 'MK', label: '🇲🇰 North Macedonia', flag: '🇲🇰' },
    { value: 'MN', label: '🇲🇳 Mongolia', flag: '🇲🇳' },
    { value: 'MO', label: '🇲🇴 Macau', flag: '🇲🇴' },
    { value: 'MP', label: '🇲🇵 Northern Mariana Islands', flag: '🇲🇵' },
    { value: 'MQ', label: '🇲🇶 Martinique', flag: '🇲🇶' },
    { value: 'MR', label: '🇲🇷 Mauritania', flag: '🇲🇷' },
    { value: 'MU', label: '🇲🇺 Mauritius', flag: '🇲🇺' },
    { value: 'MV', label: '🇲🇻 Maldives', flag: '🇲🇻' },
    { value: 'MW', label: '🇲🇼 Malawi', flag: '🇲🇼' },
    { value: 'MY', label: '🇲🇾 Malaysia', flag: '🇲🇾' },
    { value: 'MZ', label: '🇲🇿 Mozambique', flag: '🇲🇿' },
    { value: 'NA', label: '🇳🇦 Namibia', flag: '🇳🇦' },
    { value: 'NE', label: '🇳🇪 Niger', flag: '🇳🇪' },
    { value: 'NG', label: '🇳🇬 Nigeria', flag: '🇳🇬' },
    { value: 'NL', label: '🇳🇱 Netherlands', flag: '🇳🇱' },
    { value: 'NO', label: '🇳🇴 Norway', flag: '🇳🇴' },
    { value: 'NP', label: '🇳🇵 Nepal', flag: '🇳🇵' },
    { value: 'NR', label: '🇳🇷 Nauru', flag: '🇳🇷' },
    { value: 'NZ', label: '🇳🇿 New Zealand', flag: '🇳🇿' },
    { value: 'OM', label: '🇴🇲 Oman', flag: '🇴🇲' },
    { value: 'PF', label: '🇵🇫 French Polynesia', flag: '🇵🇫' },
    { value: 'PG', label: '🇵🇬 Papua New Guinea', flag: '🇵🇬' },
    { value: 'PH', label: '🇵🇭 Philippines', flag: '🇵🇭' },
    { value: 'PK', label: '🇵🇰 Pakistan', flag: '🇵🇰' },
    { value: 'PL', label: '🇵🇱 Poland', flag: '🇵🇱' },
    { value: 'PT', label: '🇵🇹 Portugal', flag: '🇵🇹' },
    { value: 'QA', label: '🇶🇦 Qatar', flag: '🇶🇦' },
    { value: 'RE', label: '🇷🇪 Réunion', flag: '🇷🇪' },
    { value: 'RO', label: '🇷🇴 Romania', flag: '🇷🇴' },
    { value: 'RS', label: '🇷🇸 Serbia', flag: '🇷🇸' },
    { value: 'RU', label: '🇷🇺 Russia', flag: '🇷🇺' },
    { value: 'RW', label: '🇷🇼 Rwanda', flag: '🇷🇼' },
    { value: 'SA', label: '🇸🇦 Saudi Arabia', flag: '🇸🇦' },
    { value: 'SB', label: '🇸🇧 Solomon Islands', flag: '🇸🇧' },
    { value: 'SC', label: '🇸🇨 Seychelles', flag: '🇸🇨' },
    { value: 'SD', label: '🇸🇩 Sudan', flag: '🇸🇩' },
    { value: 'SE', label: '🇸🇪 Sweden', flag: '🇸🇪' },
    { value: 'SG', label: '🇸🇬 Singapore', flag: '🇸🇬' },
    { value: 'SH', label: '🇸🇭 Saint Helena', flag: '🇸🇭' },
    { value: 'SI', label: '🇸🇮 Slovenia', flag: '🇸🇮' },
    { value: 'SK', label: '🇸🇰 Slovakia', flag: '🇸🇰' },
    { value: 'SL', label: '🇸🇱 Sierra Leone', flag: '🇸🇱' },
    { value: 'SM', label: '🇸🇲 San Marino', flag: '🇸🇲' },
    { value: 'SN', label: '🇸🇳 Senegal', flag: '🇸🇳' },
    { value: 'SO', label: '🇸🇴 Somalia', flag: '🇸🇴' },
    { value: 'SR', label: '🇸🇷 Surilabel', flag: '🇸🇷' },
    { value: 'SS', label: '🇸🇸 South Sudan', flag: '🇸🇸' },
    { value: 'ST', label: '🇸🇹 São Tomé and Príncipe', flag: '🇸🇹' },
    { value: 'SY', label: '🇸🇾 Syria', flag: '🇸🇾' },
    { value: 'SZ', label: '🇸🇿 Eswatini', flag: '🇸🇿' },
    { value: 'TC', label: '🇹🇨 Turks and Caicos Islands', flag: '🇹🇨' },
    { value: 'TD', label: '🇹🇩 Chad', flag: '🇹🇩' },
    { value: 'TF', label: '🇹🇫 French Southern Territories', flag: '🇹🇫' },
    { value: 'TG', label: '🇹🇬 Togo', flag: '🇹🇬' },
    { value: 'TH', label: '🇹🇭 Thailand', flag: '🇹🇭' },
    { value: 'TJ', label: '🇹🇯 Tajikistan', flag: '🇹🇯' },
    { value: 'TK', label: '🇹🇰 Tokelau', flag: '🇹🇰' },
    { value: 'TL', label: '🇹🇱 Timor-Leste', flag: '🇹🇱' },
    { value: 'TM', label: '🇹🇲 Turkmenistan', flag: '🇹🇲' },
    { value: 'TN', label: '🇹🇳 Tunisia', flag: '🇹🇳' },
    { value: 'TO', label: '🇹🇴 Tonga', flag: '🇹🇴' },
    { value: 'TR', label: '🇹🇷 Turkey', flag: '🇹🇷' },
    { value: 'TT', label: '🇹🇹 Trinidad and Tobago', flag: '🇹🇹' },
    { value: 'TV', label: '🇹🇻 Tuvalu', flag: '🇹🇻' },
    { value: 'TZ', label: '🇹🇿 Tanzania', flag: '🇹🇿' },
    { value: 'UA', label: '🇺🇦 Ukraine', flag: '🇺🇦' },
    { value: 'UG', label: '🇺🇬 Uganda', flag: '🇺🇬' },
    { value: 'UZ', label: '🇺🇿 Uzbekistan', flag: '🇺🇿' },
    { value: 'VA', label: '🇻🇦 Vatican City', flag: '🇻🇦' },
    { value: 'VC', label: '🇻🇨 Saint Vincent and the Grenadines', flag: '🇻🇨' },
    { value: 'VN', label: '🇻🇳 Vietnam', flag: '🇻🇳' },
    { value: 'VU', label: '🇻🇺 Vanuatu', flag: '🇻🇺' },
    { value: 'WF', label: '🇼🇫 Wallis and Futuna', flag: '🇼🇫' },
    { value: 'WS', label: '🇼🇸 Samoa', flag: '🇼🇸' },
    { value: 'YE', label: '🇾🇪 Yemen', flag: '🇾🇪' },
    { value: 'ZA', label: '🇿🇦 South Africa', flag: '🇿🇦' },
    { value: 'ZM', label: '🇿🇲 Zambia', flag: '🇿🇲' },
    { value: 'ZW', label: '🇿🇼 Zimbabwe', flag: '🇿🇼' },
] as const;
